<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Farukh" failures="3" tests="15" name="Test" time="257.094" errors="0" timestamp="2024-12-28T21:19:21 EST">
  <testcase classname="testcases.TC1_Registration" name="testUserRegistration" time="5.474"/>
  <testcase classname="testcases.TC2_Login" name="testLoginWithValidCredentials" time="4.492"/>
  <testcase classname="testcases.TC3_Logout" name="testLogout" time="6.04"/>
  <testcase classname="testcases.TC4_SeachProduct" name="testProductSearch" time="3.379"/>
  <testcase classname="testcases.TC5_AddToCart" name="testAddToCart" time="32.106">
    <failure type="java.lang.AssertionError" message="Success message not displayed! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Success message not displayed! expected [true] but found [false]
at testcases.TC5_AddToCart.testAddToCart(TC5_AddToCart.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testAddToCart -->
  <testcase classname="testcases.TC2_Loginddt" name="testLogin" time="5.203"/>
  <testcase classname="testcases.TC2_Loginddt" name="testLogin" time="22.117"/>
  <testcase classname="testcases.TC2_Loginddt" name="testLogin" time="3.256"/>
  <testcase classname="testcases.TC2_Loginddt" name="testLogin" time="22.057"/>
  <testcase classname="testcases.TC2_Loginddt" name="testLogin" time="3.498"/>
  <testcase classname="testcases.TC2_Loginddt" name="testLogin" time="22.176"/>
  <testcase classname="testcases.TC2_Loginddt" name="testLogin" time="22.841"/>
  <testcase classname="testcases.TC2_Loginddt" name="testLogin" time="22.551"/>
  <testcase classname="testcases.TC2_Loginddt" name="verifyAllCombinations" time="0.001">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Login succeeded with invalid credentials.">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Login succeeded with invalid credentials.
at testcases.TC2_Loginddt.verifyAllCombinations(TC2_Loginddt.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verifyAllCombinations -->
  <testcase classname="testcases.TC6_EndToEndTest" name="executeEndToEndTest" time="70.091">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at testcases.TC6_EndToEndTest.executeEndToEndTest(TC6_EndToEndTest.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- executeEndToEndTest -->
</testsuite> <!-- Test -->
